image:
  file: .gitpod/Dockerfile

tasks:
  - name: Setup workspace
    command: |
      sudo apt update -q
      sudo apt upgrade -yq
      sudo apt install -yq libgtk-3-dev python3-pip
      sudo pip3 install -Uq meson ninja

vscode:
  extensions:
    - asabil.meson
    - ccls-project.ccls